### ISSUE TITLE
Uncaught Unknown property - windowEvents

### ISSUE THREAD

**Issue by alexej-d** [kennethcachia/background-check#22]
Hi,
thank you for the great plugin. I just wanted to mention that it is not possible to set `windowEvents` to `false` without having countless JS errors. I have been trying to deactivate your plugins resize and scroll detection because I do not need it. Maybe I am doing something wrong?

**Comment by krembo99** [comment]
experiencing the exact same problem here , and as @thomas-harding said, it is only on first load of page .
Worth mentioning : 
1 - Using ( somewhat old ) Chrome ( 39.0.2171.95 )
2 - The site has a background slideshow ( and not single image/ Color )
3 - Localhost . Somehow on a webserver it seems to be ok ( maybe cached ? )

**Comment by janeschindler** [comment]
I'm getting this too. I agree that it seems to happen sometimes when loading the site for the first time.
