### ISSUE TITLE
TypeError: d.replace is not a function

### ISSUE THREAD

**Issue by rogerburkhard** [kennethcachia/background-check#43]
Hi,

thanks for this great Script! Unfortunately I have a problem to use it on a Wordpress Page. I'm getting the following Error in the Console:

Chrome: Uncaught TypeError: undefined is not a function
FF: TypeError: d.replace is not a function
      ...new RegExp("(?:^|\s)"+b+"(?!\S)","g");d=d.replace(e,"")}a.className=d.trim()}f...

Thanks for your help.

**Comment by chriseugenerodriguez** [comment]
got same issue http://demo.premiumwd.com/themes/ellion/portfolio/smoke/

code: 

if($('#theme-wrapper').hasClass('fullscreen')){
                    BackgroundCheck.init({
                         targets: "header .logo h1, header #mobile-nav svg, #theme-wrapper.fullscreen .slick-dots li",
                         images: ".full-width-container.carousal.slick-slider .slick-slide img",
                         minComplexity: 80,
                         maxDuration: 1500,
                         minOverlap: 0
                    })  
            }
