### ISSUE TITLE
Uncaught Elements not found

### ISSUE THREAD

**Issue by knubie** [kennethcachia/background-check#44]
Getting an error: `Uncaught Elements not found` when trying to initialize.

``` js
BackgroundCheck.init({
  targets: '.title'
});
```

Even though `.title` exists.

**Comment by Querschlag** [comment]
This issue still exists and has nothing to do with images.
I set my target class in the initializer and when I load the page I get this error...
There are images on my website for which I works as expected, but on I don't have an object with my target class on EVERY page.
Shouldn't the initializer fail gracefully when there's DOM object with the target class?

**Comment by dylanfisher** [comment]
I agree about failing gracefully. Seems like counter-intuitive behavior that the background-checker breaks when no images are on a page, but the targets exist.
