### ISSUE TITLE
Support for SVG Graphics

### ISSUE THREAD

**Issue by IncarVishnu** [kennethcachia/background-check#50]
Would be great to add support for svg graphics, so the script is also looking at "image-tags".
```
<image xlink:href="path/to/img" src="path/to/fallback/img"></image>
```

**Comment by kennethcachia** [comment]
Interesting... I'll mark this as a enhancement.

Thanks!

**Comment by isaacalves** [comment]
I got it working with SVG using [this method](http://css-tricks.com/cascading-svg-fill-color/).

Here's the Sass:

```
.logo {
  color: black;
  &.background--light { fill: black; }
  &.background--dark { fill: white; }
  & svg { fill: currentColor; }
}
```

with the SVG inline wrapped inside `div.logo`

**Comment by ghost** [comment]
Hi,
very nice. :-)
Thanks!
